services:
  database:
    container_name: leia-ai-database
    image: postgres:latest
    env_file:
      - ../.env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/data/postgres  

volumes:
  postgres_data:
